server:
  port: 8082
spring:
  jpa:
    show-sql: true
    hibernate:
      format sql: true
      hbm2ddl:
        auto: create
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/gangnam
    username: gangnam
    password: gangnam
    driver-class-name: com.mysql.cj.jdbc.Driver
